package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("common_user", "ids", User.class);
		arp.addMapping("common_menu", "ids", Menu.class);
		arp.addMapping("common_setting", "ids", Setting.class);
		arp.addMapping("beeneedle_process_subject", "ids", ProcessSubject.class);
	}
}
